#! /usr/bin/env bash

COMPOSE="docker-compose"

if [ $# -gt 0 ];then
    # If "art" is used, pass-thru to ”artisan“
    # inside an new container
    if [ "$1" == "art" ];then
        shift 1
        $COMPOSE run --rm app php artisan "$@"

    elif [ "$1" == "composer" ];then
        shift 1
        $COMPOSE run --rm app composer "$@"

    elif [ "$1" == "test" ];then
        shift 1
        $COMPOSE run --rm app ./vendor/bin/phpunit "$@"

    else
        $COMPOSE "$@"
    fi

else
    $COMPOSE ps
fi