version: '3.1'

services:
  app:
    image: luckwang/app
    build:
      context: ./dockerfiles/app
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    environment:
      XDEBUG_CONFIG: 'remote_enable=on'
    networks:
      - sdnet
    restart: always

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'homestead'
      MYSQL_USER: 'homestead'
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - sdnet
    restart: always

  cache:
    image: redis:5.0
    volumes:
      - redisdata:/data
    networks:
      - sdnet
    restart: always

networks:
  sdnet:
    driver: 'bridge'

volumes:
  mysqldata:
    driver: 'local'
  redisdata:
    driver: 'local'
