version: '3'

services:
  app:
    image: luckwang/app
    build:
      context: ./dockerfiles/app
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - ${APP_PORT}:80
    restart: always
    networks:
      - sdnet

  db:
    image: mysql:8.0
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'homestead'
      MYSQL_USER: 'homestead'
      MYSQL_PASSWORD: 'secret'
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - sdnet

  cache:
    image: redis:5-alpine
    volumes:
      - redisdata:/data
    networks:
      - sdnet

networks:
  sdnet:
    driver: 'bridge'

volumes:
  mysqldata:
    driver: 'local'
  redisdata:
    driver: 'local'
